[package]
name = "safe_ecs"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/BoxyUwU/safe_ecs"
repository = "https://github.com/BoxyUwU/safe_ecs"
description = "ECS written in safe code"
license = "MIT"

[dependencies]
not_ghost_cell = { path = "../not_ghost_cell" }
